version: '3'

services:
  # データベース
  db:
    build: ./db
    container_name: django_db
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=test
        - PGPASSWORD=test
        - POSTGRES_DB=django
        - DATABASE_HOST=localhost
    volumes:
        - ./db/pgdata:/var/lib/postgresql/data

  # Djangoアプリ
  web:
    build: ./web
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    tty: true
    environment:
      # 1ならデバックモード
      - DEBUG=1
      - SECRET_KEY=hoge
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_DB=django
      - DATABASE_USER=testuser
      - DATABASE_PASSWORD=test
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
