# Generated by Django 3.1.5 on 2021-01-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton_text',
            new_name='question_text',
        ),
    ]
